### ISSUE TITLE
JS procs aren't loading sounds from data stored on GCS buckets

### ISSUE THREAD

**Issue by define-private-public** [yglukhov/sound#16]
I'm having some issues with having the JS target play sound sounds from URLs.  I keep on getting these "No 'Access-Control-Allow-Origin' header is present on the requested resource." errors.

I don't think that this is error is being caused by your library, but I find it odd how I can't access the file via the `newSoundFromURL()` proc, but I can still got to it directly in a browser window.

```
XMLHttpRequest cannot load https://storage.googleapis.com/sixteenbpp/games/pucker-up-lgj2017/sounds/goalIn.ogg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://16bpp.net' is therefore not allowed access.
```

Do you have any insight what the issue might be?

**Comment by yglukhov** [comment]
That is [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS), referring to domain that your JS was not loaded from.
