### ISSUE TITLE
Loading ogg files is slow on windows

### ISSUE THREAD

**Issue by zacharycarter** [yglukhov/sound#17]
I'm running into long load times with ogg on windows. Everything seems fine with osx.

Any idea why this might be happening or how to improve it?

Thank you for the fine library!

-Zach

**Comment by zacharycarter** [comment]
Hi @yglukhov - I did some testing on this.

The issue appears to be here on Windows : https://github.com/yglukhov/sound/blob/master/sound/private/sound_al.nim#L73-L82

I'm not sure why but this code can take up to 15s to execute for a 4.2mb ogg file.

If I increase the buffer size to something like 5 MB, it executes in <2s

I'm not sure what the implications of increasing the buffer size so dramatically would be, but I'm sure you'll agree that 15s seems like an issue.

Any ideas on this one?

Thanks!

-Zach

**Comment by yglukhov** [comment]
Hey, thanks for investigating. Can I ask you to go a bit further and find whether it is `stb_vorbis_get_samples_short_interleaved` call that lags, or the reallocs. Also what time do you get on osx?

**Comment by yglukhov** [comment]
I've just updated stb_vorbis, please see if it makes any difference.

**Comment by zacharycarter** [comment]
@yglukhov I just tried with the updates - no difference.

The calls to ```stb_vorbis_get_samples_short_interleaved```  are returning in about 0.002s to 0.003s so I don't think that's the issue.

I believe it's the number of times this logic has to be looped over due to the buffer size. I don't get why the OS makes a difference here but on osx, the same ogg is read in : 1.624s

The calls to ```stb_vorbis_get_samples_short_interleaved``` on osx take the same amount of time, there are just way fewer iterations.

**Comment by yglukhov** [comment]
@zacharycarter, please note that clang on macos behaves a lot better than mingw32 in terms of optimization. If you're compiling without `-d:release` flag that could really matter. Also from my own recent experiments vcc-compiled code performs two times better than mingw32. Another trick that could work is wrapping `newSoundWithVorbis` function into push/pop pragmas that disable stacktrace and checks.

**Comment by zacharycarter** [comment]
Hi @yglukhov I've tried with and without the ```-d:release``` flag and it doesn't seem to make a difference.

I'll try doing what you suggested with ```newSoundWithVorbis```.

Would increasing the buffer size on windows be a reasonable workaround? Is there any reason the read is done in such small chunks to begin with? Just curious.

Thanks for the insight!

**Comment by zacharycarter** [comment]
Hrm I tried with the push / pop pragmas but no dice. Not sure what else can be tried besides a larger buffer at this point.

**Comment by yglukhov** [comment]
> Is there any reason the read is done in such small chunks to begin with?

No particular reason, thats just a copy-paste from somewhere. Go ahead and increase the size.
