### ISSUE TITLE
newSoundWithFile vs newSoundWithPath

### ISSUE THREAD

**Issue by treeform** [yglukhov/sound#18]
Docs say use newSoundWithPath but I think they should say use newSoundWithFile?

**Comment by arkocal** [comment]
I got stuck here too, and had to check the source code to be sure. 
I think newSoundWithPath makes more sense, you could consider using newSoundWithFile for another proc which accepts a `file` as a parameter.

**Comment by treeform** [comment]
Hey @arkocal, if you only care about win/mac/linux support with OpenAL try out https://github.com/treeform/euphony
